Repository b0tw/web-project, pull requests merged in 2020-12, with the labels that each got.

#14 [FEATURE] Implement support for partial deliverables.
  server/routers/deliverables.js
  server/routers/index.js
  server/server.js
Labels: backend, enhancement

#15 [FEATURE] Add persistent storage.
  .gitignore
  server/README.md
  server/appsettings.json
  server/entities/database/connection.js
  server/entities/database/context.js
  server/entities/database/deliverable.js
  server/entities/database/project.js
  server/entities/database/team.js
  server/entities/database/user.js
  server/entities/index.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: backend, enhancement

#17 [FIX] Update README.md with MySQL configuration instructions.
  server/README.md
Labels: backend, bug, documentation

#20 [FEATURE] Remove custom PKs and add database seeding.
  server/README.md
  server/appsettings.json
  server/entities/database/context.js
  server/entities/database/deliverable.js
  server/entities/database/jury.js
  server/entities/database/project.js
  server/entities/database/team.js
  server/entities/database/user.js
  server/seeds/initial_seed.js
Labels: backend, enhancement

#22 [FEATURE] Add authentication middleware and sessions.
  server/appsettings.json
  server/entities/api-error.js
  server/entities/database/connection.js
  server/entities/database/context.js
  server/entities/database/session.js
  server/entities/database/user.js
  server/entities/settings.js
  server/middleware/authentication-middleware.js
  server/package-lock.json
  server/package.json
  server/routers/deliverables.js
  server/routers/index.js
  server/routers/sessions.js
  server/seeds/initial_seed.js
  server/server.js
Labels: backend, enhancement

#19 [FEATURE] Add functionality to manage teams.
  server/entities/database/context.js
  server/entities/database/userteam.js
  server/routers/index.js
  server/routers/sessions.js
  server/routers/teams.js
  server/server.js
Labels: backend, enhancement

#21 [FEATURE] Add functionality to manage partial project deliverables
  server/routers/deliverables.js
Labels: backend, enhancement

#25 [FEATURE] Add users router.
  server/entities/api-error.js
  server/middleware/authentication-middleware.js
  server/routers/deliverables.js
  server/routers/index.js
  server/routers/sessions.js
  server/routers/teams.js
  server/routers/users.js
  server/server.js
Labels: backend, enhancement

#29 [FEATURE] Add exception handling middleware.
  server/middleware/exception-handling-middleware.js
  server/routers/index.js
Labels: backend, enhancement

#28 [BUG] Remove sequelize SQL output from logs.
  server/entities/database/connection.js
  server/routers/deliverables.js
  server/seeds/initial_seed.js
Labels: backend, bug

#30 [BUG] Team deletion route not working properly
  server/routers/teams.js
Labels: backend, bug

#32 [FEATURE] Update README.md to provide usage information.
  server/README.md
Labels: backend, documentation, enhancement

#31 [BUG] DB restructure
  server/entities/database/context.js
  server/entities/database/jury.js
  server/entities/database/project.js
  server/entities/database/team.js
  server/entities/database/userjury.js
  server/seeds/initial_seed.js
Labels: backend, bug

#33 [FEATURE] Refactor project related routes, add authorization, juries and grades.
  server/middleware/exception-handling-middleware.js
  server/routers/deliverables.js
  server/routers/index.js
  server/routers/sessions.js
  server/routers/teams.js
  server/routers/users.js
  server/server.js
Labels: backend, enhancement
